// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using CookApps.SpecData.Generator;


[GeneratorSpecData]
public partial class GameConfig
{
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    public string key;
    public int value;
}

[GeneratorSpecData]
public partial class Fruit
{
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    public int level;
    public string key;
    public global::ObjectTagType object_tag;
    public int score;
}

[GeneratorSpecData]
public partial class GenCoin
{
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    public int next_id;
    public int gencoin_value;
}
