// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using System.Linq;
using System.Security.Cryptography;
using System.Text;
using CookApps.SpecData.Generator;

[GeneratorSpecDataResource]
public static partial class SpecDataResourceLoader
{
    private static readonly byte[] _key = {70, 118, 55, 107, 111, 81, 81, 98, 62, 102, 112, 67, 70, 103, 90, 60};
}
