// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>


/// 과일 타입
public enum ObjectTagType
{
    FRUITS_01 = 0,
    FRUITS_02 = 1,
    FRUITS_03 = 2,
    FRUITS_04 = 3,
    FRUITS_05 = 4,
    FRUITS_06 = 5,
    FRUITS_07 = 6,
    FRUITS_08 = 7,
    FRUITS_09 = 8,
    FRUITS_10 = 9,
}

/// 보상 타입
public enum RewardType
{
    REMOVEAD = 0,
    COIN = 1,
    BOX = 2,
    NONE = 3,
}
